version: "2"
# volumes:
services:
  # gpio:
  #   restart: always
  #   build: ./gpio
  #   privileged: true
  #   # volumes:
  #   # environment:
  #   labels:
  #     io.balena.features.dbus: "1"
  #     io.balena.features.firmware: "1"
  web:
    restart: always
    build: ./web
    privileged: true
    labels:
      io.balena.features.dbus: "1"
      io.balena.features.firmware: "1"
  # scanner:
  #   build: ./scanner
  #   restart: always
  #   privileged: true
  #   network_mode: host
