FROM balenalib/%%BALENA_MACHINE_NAME%%-node:12-latest-build as build
WORKDIR /app
RUN install_packages make g++ bluetooth bluez libbluetooth-dev libudev-dev git

COPY ./package.json ./
COPY ./package-lock.json ./
RUN npm install

COPY . ./

FROM balenalib/%%BALENA_MACHINE_NAME%%-node:12-latest-run
#Set permissions to allow BLE scanning
RUN sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)

WORKDIR /app
COPY --from=build /app /app

CMD ["npm", "start"]